Styles cat's card
MissMelisa/cats pull request #10
Opened 2021-05-10 18:47 UTC by MissMelisa

add some styles to the cat's card in the main presentation
![image](https://user-images.githubusercontent.com/77803702/117709147-fb13d300-b1a6-11eb-9c9c-c60b80469e54.png)

2021-05-12 20:11 UTC, falecci commented on src/Pages/CatPresentation/index.jsx
> +    },
we don't need this

2021-05-12 20:12 UTC, falecci requested changes

2021-05-12 20:12 UTC, falecci commented on src/Pages/CatPresentation/index.jsx
> +  }
We can think of a better name for this, since we are not _clicking_.

2021-05-12 21:08 UTC, MissMelisa commented on src/Pages/CatPresentation/index.jsx
> +    },
checked it

2021-05-12 21:08 UTC, MissMelisa commented on src/Pages/CatPresentation/index.jsx
> +  }
checked it

2021-05-18 15:26 UTC, falecci approved these changes

2021-05-18 15:29 UTC, merged